<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <script>
        const MyPromise = (function(){
            // Promise 三个状态
            const PENDING = "pending"; //等待态
            const RESOLVED = "resolved"; //执行态
            const REJECTED = "rejected"; //拒绝态

            function MyPromise(executor) {
                if(typeof executor !== "function") {
                    throw new TypeError('Promise resolver ' + resolver + ' is not a function ');
                }

                var self = this; // 保存当前promise实例对象
                self.status = PENDING; // 初始化Promise当前状态
                self.value = null; // Promise的值
                self.onResolvedCallback = []; // Promise resolve时的回调函数集
                self.onRejectedCallback = []; // Promise reject时的回调函数集                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        

                function resolve(value){
                    if(value instanceof MyPromise){
                        return value.then(resolve, reject);
                    }
                    // 为什么resolve 加setTimeout?
                    // 2.2.4规范 onResolved(onFulfilled) 和 onRejected 只允许在 execution context 栈仅包含平台代码时运行.
                    // 注1 这里的平台代码指的是引擎、环境以及 promise 的实施代码。实践中要确保 onResolved 和 onRejected 方法异步执行，
                    // 且应该在 then 方法被调用的那一轮事件循环之后的新执行栈中执行。
                    setTimeout(function () {
                        if(self.status === PENDING){ 
                            // 只能由pedning状态 => resolved状态 (避免调用多次resolve reject)
                            self.status = RESOLVED; //状态改变
                            self.value = value; //执行态值
                            self.onResolvedCallback.map(cb => cb(value)); //如果已调用then注册回调方法，这里进行调用 resolve 回调对应onResolved函数
                        }
                    })
                }

                function reject(reason){ // reason失败态时接收的拒因
                    setTimeout(function () {
                        if(self.status === PENDING){
                            // 只能由pedning状态 => resolved状态 (避免调用多次resolve reject)
                            self.status = REJECTED; //状态改变
                            self.value = reason; //拒绝态原因
                            self.onRejectedCallback.map(cb => cb(value)); //如果已调用then注册回调方法，这里进行调用 rejected 回调对应onRejected函数
                        }
                    })
                }

                // 捕获在excutor执行器中抛出的异常
                try {
                    executor(resolve, reject);
                } catch (e) {
                    reject(e);
                }
            }
            
            /**
            * resolve中值得几种情况：
            * 1.普通值
            * 2.promise对象
            * 3.thenable对象/函数 （不是promise对象，但是拥有自己的then方法的对象或者函数）
            */

            /**
            * 对resolve 进行改造增强 针对resolve中不同值情况 进行处理
            * @param  {promise} promise2 promise1.then方法返回的新的promise对象
            * @param  {[type]} x         promise1中onResolved的返回值
            * @param  {[type]} resolve   promise2的resolve方法
            * @param  {[type]} reject    promise2的reject方法
            */

            function resolvePromise(promise2, x, resolve, reject) {
                if(promise2 === x){ // 如果onResolved中返回的x就是promise2，就会导致循环引用报错
                    return reject(new TypeError('循环引用'));
                }
                let called = false; //避免循环多次调用
                // 
                if(x instanceof Promise){
                    if(x.status === PENDING) {
                        x.then(y => {// 如果为等待态需等待直至 x 被执行或拒绝 并解析y值
                            resolvePromise(promise2, y, resolve, reject);
                        }, reason => {
                            reject(reason);
                        })
                    } else {
                        // 如果 x 已经处于执行态/拒绝态(值已经被解析为普通值)，用相同的值执行传递下去 promise
                        x.then(resolve, reject);
                    }
                } else if (x != null && ((typeof x === 'object') || (typeof x === 'function'))) {
                    try { // 是否是thenable对象（具有then方法的对象/函数）
                        let then = x.then;
                        if(typeof then === 'function'){
                            then.call(x, y => {
                                if(called) return;
                                called = true;
                                resolvePromise(promise2, y, resolve, reject);
                            })
                        } else { // 说明是一个普通对象/函数
                            resolve(x);
                        }
                    } catch (e) {
                        if(called) return;
                        called = true;
                        reject(e);
                    }
                } else {
                    resolve(x);
                }

            }

            MyPromise.prototype.then = function(onResolved, onRejected){
                var self = this;
                var promise2;

                // 根据标准， 如果then的参数不是function，则我们需要忽略它，此处以如下方式处理
                onResolved = typeof onResolved === "function" ? onResolved : value => value;
                onRejected = typeof onRejected === "function" ? onRejected : reason => { throw reason; };

                // then里面的RESOLVED/REJECTED状态时，为什么要加setTimeout ?
                // 原因:
                // 其一 2.2.4规范 要确保 onResolved 和 onRejected 方法异步执行(且应该在 then 方法被调用的那一轮事件循环之后的新执行栈中执行) 所以要在resolve里加上setTimeout
                // 其二 2.2.6规范 对于一个promise，它的then方法可以调用多次.
                // 总之都是 让then方法异步执行 也就是确保onResolved/onRejected异步执行


                if(self.status === PENDING){ // 等待态
                    // 如果当前的状态还处于pending状态，我们并不能确定调用onResolved还是onRejected，
                    // 只能等到Promise的状态确定后，才能确实如何处理。
                    // 所以当异步调用resolve/rejected时 将onFulfilled/onRejected收集暂存到集合中
                    return promise2 = new MyPromise(function(resolve, reject) {
                        self.onResolvedCallback.push(function(value){
                            try {
                                var x = onResolved(self.value);
                                resolvePromise(promise2, x, resolve, reject);
                            } catch (e) {
                                reject(e);
                            }
                        })
                        self.onRejectedCallback.push(function(value){
                            try {
                                var x = onRejected(self.value);
                                resolvePromise(promise2, x, resolve, reject);
                            } catch (e) {
                                reject(e);
                            }
                        })
                    });
                }

                if(self.status === RESOLVED){ // 成功态
                    // 如果promise1(此处指this/self)的状态已经确定并且是resolved，我们调用onResolved
                    // 考虑到onResolved函数执行有可能throw，所以我们将其包在try/catch块里
                    return promise2 = new MyPromise(function(resolve, reject) {
                        setTimeout(()=>{
                            try {
                                var x = onResolved(self.value);
                                resolvePromise(promise2, x, resolve, reject);
                            } catch (e) {
                                // 捕获前面onResolved中抛出的异常 then(onResolved, onRejected);
                                reject(e);
                            }
                        });
                    });
                }

                if(self.status === REJECTED){ // 失败态
                    // 如果promise1(此处指this/self)的状态已经确定并且是rejected，我们调用onRejected
                    // 考虑到onRejected函数执行有可能throw，所以我们将其包在try/catch块里
                    return promise2 = new MyPromise(function(resolve, reject) {
                        setTimeout(()=>{
                            try {
                                var x = onRejected(self.value);
                                resolvePromise(promise2, x, resolve, reject);
                            } catch (e) {
                                // 捕获前面onResolved中抛出的异常 then(onResolved, onRejected);
                                reject(e);
                            }
                        });
                    });
                }
            }

            MyPromise.prototype.catch = function(onRejected) {
                return this.then(null, onRejected);
            }

            return MyPromise;
        })();
        console.log(MyPromise);
    </script>
</body>
</html>